# Site Settings
title: Social Distance Radio
email: socialdistanceradio2020@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  We lonely.
url: "socialdistanceradio.org"
# baseurl: "/website" # the subpath of your site, e.g. /blog
# url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: radiosocialdist
github_username:  social-distance-radio

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
